# -*- coding: utf-8 -*-
"""clientes.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kPiBQIyjwhPTHwbKesbNmqF9EgPwgdPA

#Cliente
Cliente en consola para consumir la API Libros Top 100.
Permite consultar, modificar y verificar libros usando endpoints REST.
"""

import requests

BASE_URL = "http://127.0.0.1:8000"  # URL base del servidor local

# Funciones cliente
def consultar_libros():
    """Consulta todos los libros disponibles."""
    url = f"{BASE_URL}/get-books"
    response = requests.get(url)
    response.raise_for_status()
    data = response.json()
    print(f"Total de libros: {data['total_libros']}")
    for libro in data["libros"][:5]:
        print(f"📘 {libro['title']} — {libro['author']}")
    print("...")


def modificar_libro():
    """Permite modificar un libro existente."""
    title = input("Ingrese el título del libro a modificar: ")
    author = input("Ingrese el autor: ")
    libro_modificado = {
        "author": input("Nuevo autor: "),
        "country": input("País: "),
        "imageLink": input("Enlace de imagen: "),
        "language": input("Idioma: "),
        "link": input("Enlace Wikipedia: "),
        "pages": int(input("Cantidad de páginas: ")),
        "title": input("Nuevo título: "),
        "year": int(input("Año de publicación: "))
    }
    response = requests.put(f"{BASE_URL}/update-book", params={"title": title, "author": author}, json=libro_modificado)
    print(response.json())


def verificar_libro():
    """Verifica si un libro está en la lista."""
    title = input("Ingrese el título: ")
    author = input("Ingrese el autor: ")
    response = requests.get(f"{BASE_URL}/check-book", params={"title": title, "author": author})
    print(response.json())



# Menú interactivo
if __name__ == "__main__":
    while True:
        print("\n=== MENÚ DE OPCIONES ===")
        print("1. Consultar todos los libros")
        print("2. Modificar un libro")
        print("3. Verificar si un libro está en la lista")
        print("4. Salir")
        opcion = input("Seleccione una opción: ")

        try:
            if opcion == '1':
                consultar_libros()
            elif opcion == '2':
                modificar_libro()
            elif opcion == '3':
                verificar_libro()
            elif opcion == '4':
                print("Saliendo del programa...")
                break
            else:
                print("❌ Opción no válida.")
        except Exception as e:
            print(f"⚠️ Error: {e}")