# -*- coding: utf-8 -*-
"""API-TP-Redes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IPYfM8c-uyP_5L6rx68hga7nMo2Hrohj

# Redes de datos
# Año: 2025

# API Top 100 Libros
API desarrollada en FastAPI para administrar una lista de los 100 mejores libros.
Permite consultar, agregar, modificar y eliminar libros de un archivo JSON local.
El dataset se descarga automáticamente desde GitHub si no está disponible.

Instalamos dependencias e importamos librerías.
"""

!pip install fastapi
!pip install uvicorn

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, HttpUrl
import requests
import json
import os

"""Configuración inicial."""

app = FastAPI(title="API Libros Top 100", version="1.0")
data_file = 'books.json'
URL_JSON = 'https://raw.githubusercontent.com/benoitvallon/100-best-books/master/books.json'

"""Modelo de datos (Pydantic)."""

class Libro(BaseModel):
    author: str
    country: str
    imageLink: HttpUrl
    language: str
    link: HttpUrl
    pages: int
    title: str
    year: int

"""Funciones auxiliares.

"""

def descarga_archivo(url: str, ruta_archivo: str):
    """Descarga el archivo JSON desde la URL indicada."""
    response = requests.get(url)
    if response.status_code == 200:
        with open(ruta_archivo, 'wb') as file:
            file.write(response.content)
        print('✅ Archivo JSON descargado con éxito.')
    else:
        raise HTTPException(status_code=500, detail="Error al descargar el archivo JSON.")


def cargar_data():
    """Carga los datos del archivo JSON local."""
    if not os.path.exists(data_file):
        descarga_archivo(URL_JSON, data_file)
    with open(data_file, 'r', encoding='utf-8') as archivo:
        return json.load(archivo)


def guardar_data(data):
    """Guarda los datos actualizados en el archivo JSON."""
    with open(data_file, 'w', encoding='utf-8') as archivo:
        json.dump(data, archivo, indent=4, ensure_ascii=False)

"""Endpoints de la API."""

@app.get("/get-books")
def obtener_libros():
    """Obtiene la lista completa de libros."""
    data = cargar_data()
    return {"total_libros": len(data), "libros": data}


@app.get("/check-book")
def verificar_libro(title: str, author: str):
    """Verifica si un libro específico está en la lista."""
    data = cargar_data()
    for libro in data:
        if libro.get("title") == title and libro.get("author") == author:
            return {"message": f"📖 El libro '{title}' de '{author}' está en la lista."}
    raise HTTPException(status_code=404, detail=f"No se encontró el libro '{title}' de '{author}'.")


@app.post("/create-book")
def crear_libro(nuevo_libro: Libro):
    """Agrega un nuevo libro al archivo JSON."""
    data = cargar_data()
    nuevo_libro_dict = nuevo_libro.dict()
    nuevo_libro_dict["id"] = len(data) + 1
    data.append(nuevo_libro_dict)
    guardar_data(data)
    return {"message": "✅ Libro agregado exitosamente.", "Libro": nuevo_libro_dict}


@app.put("/update-book")
def modificar_libro(title: str, author: str, libro_actualizado: Libro):
    """Modifica la información de un libro existente."""
    data = cargar_data()
    for idx, libro in enumerate(data):
        if libro.get("title") == title and libro.get("author") == author:
            data[idx] = libro_actualizado.dict()
            guardar_data(data)
            return {"message": f"✏️ Libro '{title}' de '{author}' modificado con éxito.", "Libro": libro_actualizado}
    raise HTTPException(status_code=404, detail=f"No se encontró un libro con título '{title}' y autor '{author}'.")


@app.delete("/delete-book")
def eliminar_libro(title: str, author: str):
    """Elimina un libro del JSON por título y autor."""
    data = cargar_data()
    for libro in data:
        if libro.get("title") == title and libro.get("author") == author:
            data.remove(libro)
            guardar_data(data)
            return {"message": f"🗑️ Libro '{title}' de '{author}' eliminado correctamente."}
    raise HTTPException(status_code=404, detail="Libro no encontrado.")

"""Inicialización del archivo JSON"""

if not os.path.exists(data_file):
    descarga_archivo(URL_JSON, data_file)
